[program:analytics-flush]
command=php artisan analytics:flush --daemon
directory=/var/www/apps/analytics-service
numprocs=1
autostart=true
autorestart=true
stopwaitsecs=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
